{
 "title": "Chronicle",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Chronicle-fs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "FS memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"metrics/chronicle-fs\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "FS CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"metrics/chronicle-fs\"}) / sum(machine_cpu_cores) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Go routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"metrics/chronicle-fs\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Logs writes",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(chronicle_fs_logs_count)*60",
     "legendFormat": "{{app}}/{{element}}"
    }
   ]
  },
  { "title": "Cloud-System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Logs reads",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cloud_system_http_request_count{path=~\"/api/logs.*\", user!=\"\"})*60",
     "legendFormat": "{{path}} - {{user}}"
    }
   ]
  }
 ]
}