{
 "title": "Clickhouse internal exporter",
 "description": "Clickhouse metrics for internal (embedded, <prometheus>) exporter",
 "tags": [
  "clickhouse",
  "db"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values(ClickHouseProfileEvents_Query, environment)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ClickHouseProfileEvents_Query{environment=\"$environment\"}, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Query",
   "type": "graph",
   "description": "Number of queries to be interpreted and potentially executed. Does not include queries that failed to parse or were rejected due to AST size limits, quota limits or limits on the number of simultaneously running queries. May include internal queries initiated by ClickHouse itself. Does not count subqueries.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_Query{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Select Query",
   "type": "graph",
   "description": "Only for SELECT queries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Insert Query",
   "type": "graph",
   "description": "Only for INSERT queries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQuery{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "description": "Number of Replicated tables that are leaders. Leader replica is responsible for assigning merges, cleaning old blocks for deduplications and a few more bookkeeping tasks. There may be no more than one leader across all replicas at one moment of time. If there is no leader it will be elected soon or it indicate an issue.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_LeaderReplica{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ReadOnly replica",
   "type": "singlestat",
   "description": "Number of Replicated tables that are currently in readonly state due to re-initialization after ZooKeeper session loss or due to startup without ZooKeeper configured.",
   "gridPos": { "h": 8, "w": 2, "x": 11, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ClickHouseMetrics_ReadonlyReplica{environment=\"$environment\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "graph",
   "description": "Number of data parts checking for consistency\n\nNumber of data parts being fetched from replica\n\nNumber of data parts being sent to replicas",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReplicatedChecks{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "Checking for consistency on {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedFetch{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "Fetched from replica on {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedSend{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "Sent to replicas from {{instance}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "tcp - Number of connections to TCP server (clients with native interface), also included server-server distributed query connections\n\nhttp - Number of connections to HTTP server\n\ninterserver - Number of connections from other replicas to fetch parts\n\nmysql - Number of client connections using MySQL protocol",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "tcp {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "http {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_InterserverConnection{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "interserver {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_MySQLConnection{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "mysql {{instance}}"
    }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "description": "Number of active tasks in BackgroundProcessingPool (merges, mutations, fetches, or replication queue bookkeeping)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundPoolTask{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "description": "Number of files opened.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_FileOpen{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "description": "Number of uncompressed bytes (the number of bytes after decompression) read from compressed sources (files, network).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBytes{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Total amount of memory (bytes) allocated by the server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Read/Write Syscalls",
   "type": "graph",
   "description": "Number of read (read, pread, io_getevents, etc.) syscalls in fly\n\nNumber of write (write, pwrite, io_getevents, etc.) syscalls in fly",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_Read{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "Read {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_Write{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "Write {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Read/Write with a File Descriptor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "Number of Reads {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "Failed Reads {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "Number of Writes {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteFailed{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "Failed Writes {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes of Read/Write with a File Descriptor",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "Bytes of Reads {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "Bytes of Writes {{instance}}"
    }
   ]
  },
  {
   "title": "Cache Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MarkCacheMisses{environment=\"$environment\",job=\"$job\"}[5m])",
     "legendFormat": "misses {{instance}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_MarkCacheHits{environment=\"$environment\",job=\"$job\"}[5m])",
     "legendFormat": "hits {{instance}}"
    }
   ]
  },
  { "title": "ReplicatedMergeTree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Parts of ReplicatedMergeTree Merged",
   "type": "graph",
   "description": "Number of times data parts of ReplicatedMergeTree tables were successfully merged.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMerges{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mutations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReplicatedPartMutations{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "MergeTree", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Selected Ranges",
   "type": "graph",
   "description": "ClickHouseProfileEvents_SelectedRanges",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_SelectedRanges{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Selected Marks",
   "type": "graph",
   "description": "Number of marks (index granules) selected to read from a MergeTree table.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_SelectedMarks{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "description": "Number of launched background merges.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_Merge{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_Merge{environment=\"$environment\",job=\"$job\"}",
     "legendFormat": "merge {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_MergedRows{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "rate {{job}}"
    }
   ]
  },
  {
   "title": "Merges Time",
   "type": "graph",
   "description": "Total time spent for background merges.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 81 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MergesTimeMilliseconds{environment=\"$environment\",job=\"$job\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}