package db2

// This file is automatically generated, manual editing is not recommended.

type CertProviderVariantT uint16

const (
	CertProviderVariant_Timoni      CertProviderVariantT = 1
	CertProviderVariant_LetsEncrypt CertProviderVariantT = 2
	CertProviderVariant_Azure       CertProviderVariantT = 3
)

var translationMapEN_CertProviderVariant = map[CertProviderVariantT]string{
	1: "Timoni",
	2: "LetsEncrypt",
	3: "Azure",
}

func (o CertProviderVariantT) EN() string { return translationMapEN_CertProviderVariant[o] }

var translationMapPL_CertProviderVariant = map[CertProviderVariantT]string{
	1: "Timoni",
	2: "LetsEncrypt",
	3: "Azure",
}

func (o CertProviderVariantT) PL() string { return translationMapPL_CertProviderVariant[o] }
