package db2

// This file is automatically generated, manual editing is not recommended.

type DNSProviderVariantT uint16

const (
	DNSProviderVariant_Timoni     DNSProviderVariantT = 1
	DNSProviderVariant_Azure      DNSProviderVariantT = 2
	DNSProviderVariant_Cloudflare DNSProviderVariantT = 5
)

var translationMapEN_DNSProviderVariant = map[DNSProviderVariantT]string{
	1: "Timoni",
	2: "Azure",
	5: "Cloudflare",
}

func (o DNSProviderVariantT) EN() string { return translationMapEN_DNSProviderVariant[o] }

var translationMapPL_DNSProviderVariant = map[DNSProviderVariantT]string{
	1: "Timoni",
	2: "Azure",
	5: "Cloudflare",
}

func (o DNSProviderVariantT) PL() string { return translationMapPL_DNSProviderVariant[o] }
