package db2

// This file is automatically generated, manual editing is not recommended.

type ImageBuilderVariantT uint16

const (
	ImageBuilderVariant_Timoni         ImageBuilderVariantT = 1
	ImageBuilderVariant_TimoniExternal ImageBuilderVariantT = 2
)

var translationMapEN_ImageBuilderVariant = map[ImageBuilderVariantT]string{
	1: "Timoni",
	2: "TimoniExternal",
}

func (o ImageBuilderVariantT) EN() string { return translationMapEN_ImageBuilderVariant[o] }

var translationMapPL_ImageBuilderVariant = map[ImageBuilderVariantT]string{
	1: "Timoni",
	2: "TimoniExternal",
}

func (o ImageBuilderVariantT) PL() string { return translationMapPL_ImageBuilderVariant[o] }
