package db2

// This file is automatically generated, manual editing is not recommended.

import (
	"encoding/json"
	"fmt"
	"time"

	"fyne.io/fyne/v2/data/binding"
	"github.com/lukx33/lwhelper"
	"github.com/lukx33/lwhelper/out"
	"gorm.io/gorm"
)

var tmpCertProvider = lwhelper.ID()

type CertProvider interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	ID() string
	Created() int64
	Updated() int64

	Azure_ClientID() string
	SetAzure_ClientID(value string) out.Info
	Azure_ClientSecret() string
	SetAzure_ClientSecret(value string) out.Info
	Azure_PrivateZone() bool
	SetAzure_PrivateZone(value bool) out.Info
	Azure_ResourceGroup() string
	SetAzure_ResourceGroup(value string) out.Info
	Azure_SubscriptionID() string
	SetAzure_SubscriptionID(value string) out.Info
	Azure_TenantID() string
	SetAzure_TenantID(value string) out.Info
	Enabled() bool
	SetEnabled(value bool) out.Info
	LetsEncrypt_ClientPrivateKey() []byte
	SetLetsEncrypt_ClientPrivateKey(value []byte) out.Info
	LetsEncrypt_Email() string
	SetLetsEncrypt_Email(value string) out.Info
	LetsEncrypt_Key() string
	SetLetsEncrypt_Key(value string) out.Info
	LetsEncrypt_URL() string
	SetLetsEncrypt_URL(value string) out.Info
	Name() string
	SetName(value string) out.Info
	Organization() Organization
	SetOrganization(value Organization) out.Info
	Variant() CertProviderVariantT
	SetVariant(value CertProviderVariantT) out.Info
	Delete() out.Info
}
type certProviderS struct {
	out.DontUseMeInfoS `gorm:"-"`

	IDC      string `gorm:"column:ID;primaryKey"`
	CreatedC int64  `gorm:"column:Created;autoCreateTime"`
	UpdatedC int64  `gorm:"column:Updated;autoUpdateTime"`

	Azure_ClientIDC               string               `gorm:"column:Azure_ClientID"`
	Azure_ClientSecretC           string               `gorm:"column:Azure_ClientSecret"`
	Azure_PrivateZoneC            bool                 `gorm:"column:Azure_PrivateZone"`
	Azure_ResourceGroupC          string               `gorm:"column:Azure_ResourceGroup"`
	Azure_SubscriptionIDC         string               `gorm:"column:Azure_SubscriptionID"`
	Azure_TenantIDC               string               `gorm:"column:Azure_TenantID"`
	EnabledC                      bool                 `gorm:"column:Enabled"`
	LetsEncrypt_ClientPrivateKeyC []byte               `gorm:"column:LetsEncrypt_ClientPrivateKey"`
	LetsEncrypt_EmailC            string               `gorm:"column:LetsEncrypt_Email"`
	LetsEncrypt_KeyC              string               `gorm:"column:LetsEncrypt_Key"`
	LetsEncrypt_URLC              string               `gorm:"column:LetsEncrypt_URL"`
	NameC                         string               `gorm:"column:Name"`
	OrganizationC                 string               `gorm:"column:Organization"`
	VariantC                      CertProviderVariantT `gorm:"column:Variant"`
}

func (certProviderS) TableName() string {
	return "CertProvider"
}

// ---

func (o *certProviderS) AfterFind(tx *gorm.DB) error {
	return nil
}

// ---

func (o *certProviderS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *certProviderS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

func (o *certProviderS) AddListener(l binding.DataListener) {
	fmt.Println("CertProvider AddListener")
}

func (o *certProviderS) RemoveListener(l binding.DataListener) {
	fmt.Println("CertProvider RemoveListener")
}

func (o *certProviderS) Delete() out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Where("ID = ?", o.IDC).Delete(&certProviderS{}).Error
	if err != nil {
		return out.New(err)
	}

	return out.NewSuccess()
}

func certProviderCreateOrUpdate(srcB []byte) {

	src := &certProviderS{}
	json.Unmarshal(srcB, src)
	id := src.IDC
	// src.InfoPrint()

	if id == "" {
		panic("cos tu jest nie tak")
	}

	srcMap := map[string]any{}
	json.Unmarshal(src.InfoJSON(), &srcMap)
	delete(srcMap, "trace")
	delete(srcMap, "result")
	delete(srcMap, "vars")
	delete(srcMap, "IDC")
	// out.PrintJSON(srcMap)

	dbLock.Lock()
	defer dbLock.Unlock()

	var exists bool
	if out.New(dbConnection.Model(&certProviderS{}).Select("count(*) > 0").
		Where("id = ?", id).Find(&exists).Error).NotValid() {
		return
	}
	if !exists {
		// new item, creating
		// fmt.Println("new item")
		out.New(dbConnection.Create(src).Error)
		return
	}

	// looking for changes
	// fmt.Println("changes")
	out.New(dbConnection.Model(&certProviderS{}).Where("ID = ?", id).Updates(srcMap).Error)
}

// ---
// ID

func (o *certProviderS) ID() string {
	if o == nil {
		return ""
	}
	return o.IDC
}

// ---
// Created

func (o *certProviderS) Created() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedC
}

// ---
// Updated

func (o *certProviderS) Updated() int64 {
	if o == nil {
		return 0
	}
	return o.UpdatedC
}

// ---
// Azure_ClientID

func (o *certProviderS) Azure_ClientID() string {
	if o == nil {
		return ""
	}
	return o.Azure_ClientIDC
}

func (o *certProviderS) SetAzure_ClientID(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_ClientIDC
	o.Azure_ClientIDC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Azure_ClientID", value).Error
	if err != nil {
		o.Azure_ClientIDC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_ClientSecret

func (o *certProviderS) Azure_ClientSecret() string {
	if o == nil {
		return ""
	}
	return o.Azure_ClientSecretC
}

func (o *certProviderS) SetAzure_ClientSecret(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_ClientSecretC
	o.Azure_ClientSecretC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Azure_ClientSecret", value).Error
	if err != nil {
		o.Azure_ClientSecretC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_PrivateZone

func (o *certProviderS) Azure_PrivateZone() bool {
	if o == nil {
		return false
	}
	return o.Azure_PrivateZoneC
}

func (o *certProviderS) SetAzure_PrivateZone(value bool) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_PrivateZoneC
	o.Azure_PrivateZoneC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Azure_PrivateZone", value).Error
	if err != nil {
		o.Azure_PrivateZoneC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_ResourceGroup

func (o *certProviderS) Azure_ResourceGroup() string {
	if o == nil {
		return ""
	}
	return o.Azure_ResourceGroupC
}

func (o *certProviderS) SetAzure_ResourceGroup(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_ResourceGroupC
	o.Azure_ResourceGroupC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Azure_ResourceGroup", value).Error
	if err != nil {
		o.Azure_ResourceGroupC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_SubscriptionID

func (o *certProviderS) Azure_SubscriptionID() string {
	if o == nil {
		return ""
	}
	return o.Azure_SubscriptionIDC
}

func (o *certProviderS) SetAzure_SubscriptionID(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_SubscriptionIDC
	o.Azure_SubscriptionIDC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Azure_SubscriptionID", value).Error
	if err != nil {
		o.Azure_SubscriptionIDC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_TenantID

func (o *certProviderS) Azure_TenantID() string {
	if o == nil {
		return ""
	}
	return o.Azure_TenantIDC
}

func (o *certProviderS) SetAzure_TenantID(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_TenantIDC
	o.Azure_TenantIDC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Azure_TenantID", value).Error
	if err != nil {
		o.Azure_TenantIDC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Enabled

func (o *certProviderS) Enabled() bool {
	if o == nil {
		return false
	}
	return o.EnabledC
}

func (o *certProviderS) SetEnabled(value bool) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.EnabledC
	o.EnabledC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Enabled", value).Error
	if err != nil {
		o.EnabledC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// LetsEncrypt_ClientPrivateKey

func (o *certProviderS) LetsEncrypt_ClientPrivateKey() []byte {
	if o == nil {
		return nil
	}
	return o.LetsEncrypt_ClientPrivateKeyC
}

func (o *certProviderS) SetLetsEncrypt_ClientPrivateKey(value []byte) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.LetsEncrypt_ClientPrivateKeyC
	o.LetsEncrypt_ClientPrivateKeyC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("LetsEncrypt_ClientPrivateKey", value).Error
	if err != nil {
		o.LetsEncrypt_ClientPrivateKeyC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// LetsEncrypt_Email

func (o *certProviderS) LetsEncrypt_Email() string {
	if o == nil {
		return ""
	}
	return o.LetsEncrypt_EmailC
}

func (o *certProviderS) SetLetsEncrypt_Email(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.LetsEncrypt_EmailC
	o.LetsEncrypt_EmailC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("LetsEncrypt_Email", value).Error
	if err != nil {
		o.LetsEncrypt_EmailC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// LetsEncrypt_Key

func (o *certProviderS) LetsEncrypt_Key() string {
	if o == nil {
		return ""
	}
	return o.LetsEncrypt_KeyC
}

func (o *certProviderS) SetLetsEncrypt_Key(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.LetsEncrypt_KeyC
	o.LetsEncrypt_KeyC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("LetsEncrypt_Key", value).Error
	if err != nil {
		o.LetsEncrypt_KeyC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// LetsEncrypt_URL

func (o *certProviderS) LetsEncrypt_URL() string {
	if o == nil {
		return ""
	}
	return o.LetsEncrypt_URLC
}

func (o *certProviderS) SetLetsEncrypt_URL(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.LetsEncrypt_URLC
	o.LetsEncrypt_URLC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("LetsEncrypt_URL", value).Error
	if err != nil {
		o.LetsEncrypt_URLC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Name

func (o *certProviderS) Name() string {
	if o == nil {
		return ""
	}
	return o.NameC
}

func (o *certProviderS) SetName(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.NameC
	o.NameC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Name", value).Error
	if err != nil {
		o.NameC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Organization

func (o *certProviderS) Organization() Organization {
	if o == nil {
		return nil
	}
	return OrganizationGetByID(o.OrganizationC)
}

func (o *certProviderS) SetOrganization(value Organization) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.OrganizationC
	o.OrganizationC = value.ID()

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Organization", value.ID()).Error
	if err != nil {
		o.OrganizationC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Variant

func (o *certProviderS) Variant() CertProviderVariantT {
	if o == nil {
		return 0
	}
	return o.VariantC
}

func (o *certProviderS) SetVariant(value CertProviderVariantT) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.VariantC
	o.VariantC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&certProviderS{}).Where("ID = ?", o.IDC).Update("Variant", value).Error
	if err != nil {
		o.VariantC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ----------------------------------------------------- table list:

type certProviderList interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	Length() int
	First() CertProvider
	GetByID(id string) CertProvider
	Iter() []CertProvider
	Refresh() out.Info
	SetWhere(where string) out.Info
	SetOrder(order string) out.Info
	SetOffset(offset int) out.Info
	SetLimit(limit int) out.Info

	AddListener(dl binding.DataListener)
	RemoveListener(dl binding.DataListener)
	GetItem(index int) (binding.DataItem, error)
}

type certProviderListS struct {
	out.DontUseMeInfoS

	query        req_listQueryS
	M            map[string]*certProviderS
	IDs          []string
	IDtoIdx      map[string]int
	dataListener map[binding.DataListener]bool
}

//---

func (o *certProviderListS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *certProviderListS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

func (o *certProviderListS) AddListener(dl binding.DataListener) {
	// fmt.Println("CertProviderList AddListener")
	if o.dataListener == nil {
		o.dataListener = map[binding.DataListener]bool{}
	}
	o.dataListener[dl] = true
}

func (o *certProviderListS) RemoveListener(dl binding.DataListener) {
	// fmt.Println("CertProviderList RemoveListener")
	delete(o.dataListener, dl)
}

func (o *certProviderListS) GetItem(index int) (binding.DataItem, error) {
	// fmt.Println("CertProviderList GetItem")
	return o.M[o.IDs[index]], nil
}

func (o *certProviderListS) Length() int {
	// fmt.Println("CertProviderList Length")
	return len(o.IDs)
}

func (o *certProviderListS) SetWhere(where string) out.Info {
	o.query = req_listQueryS{
		Where: where,
	}
	return o.Refresh()
}

func (o *certProviderListS) SetOrder(order string) out.Info {
	o.query = req_listQueryS{
		Order: order,
	}
	return o.Refresh()
}

func (o *certProviderListS) SetOffset(offset int) out.Info {
	o.query = req_listQueryS{
		Offset: offset,
	}
	return o.Refresh()
}

func (o *certProviderListS) SetLimit(limit int) out.Info {
	o.query = req_listQueryS{
		Limit: limit,
	}
	return o.Refresh()
}

//---

func CertProviderList(where, order string, offset, limit int) certProviderList {

	response := &certProviderListS{
		query: req_listQueryS{
			Where:  where,
			Order:  order,
			Offset: offset,
			Limit:  limit,
		},
	}

	if where == "nil" {
		return response
	}

	response.Refresh()
	return response
}

func (o *certProviderListS) Refresh() out.Info {

	if o.query.Where == "nil" {
		return o
	}

	res := &certProviderListS{
		query:        o.query,
		IDs:          []string{},
		IDtoIdx:      map[string]int{},
		M:            map[string]*certProviderS{},
		dataListener: o.dataListener,
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	st := dbConnection.Model(&certProviderS{})
	if o.query.Where != "" {
		st.Where(o.query.Where)
	}
	if o.query.Order == "" {
		o.query.Order = "Created"
	}
	if o.query.Limit == 0 {
		o.query.Limit = 30
	}

	responseList := []*certProviderS{}
	if out.CatchError(res,
		st.Order(o.query.Order).Offset(o.query.Offset).Limit(o.query.Limit).Find(&responseList).Error,
	).NotValid() {
		return res
	}
	// out.PrintJSON(responseList)

	for idx, entry := range responseList {
		res.IDs = append(res.IDs, entry.IDC)
		res.IDtoIdx[entry.IDC] = idx
		res.M[entry.IDC] = entry
	}

	out.CatchError(res, nil)
	*o = *res

	for dl := range o.dataListener {
		// fmt.Println(">>>>>>>>>>>>>>>>>> dataListener", dl)
		dl.DataChanged()
	}
	return res
}

func (o *certProviderListS) First() CertProvider {
	for _, obj := range o.M {
		return out.CatchError(obj, nil)
	}

	res := &certProviderS{}
	res.InfoAddTrace(out.NotFound, "", 0)
	return res
}

func (o *certProviderListS) GetByID(id string) CertProvider {
	res, exist := o.M[id]
	if !exist {
		res.InfoAddTrace(out.NotFound, "", 0)
		return res
	}
	return out.CatchError(res, nil)
}

func (o *certProviderListS) Iter() []CertProvider {

	if o.NotValid() {
		return nil
	}

	res := []CertProvider{}
	for _, id := range o.IDs {
		res = append(res, out.CatchError(o.M[id], nil))
	}
	return res
}

// ---

func CertProviderGetByID(key string) CertProvider {

	res := &certProviderS{}
	if key == "" {
		res.InfoAddTrace(out.NotFound, "", 0)
		return res
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	out.CatchError(res, dbConnection.Where("ID = ?", key).First(res).Error)

	if res.NotValid() && res.InfoLastTrace().Message == "record not found" {
		res.Result = out.NotFound
	}

	return res
}

//---

func CertProviderCreate(
	Name string,
	Organization Organization,
	Variant CertProviderVariantT,
) CertProvider {

	// TODO: Input data validation

	now := time.Now()
	obj := &certProviderS{
		IDC:           lwhelper.ID(),
		CreatedC:      now.Unix(),
		UpdatedC:      now.Unix(),
		NameC:         Name,
		OrganizationC: Organization.ID(),
		VariantC:      Variant,
	}

	obj.Azure_PrivateZoneC = false
	obj.EnabledC = true

	// Saving data to the database
	dbLock.Lock()
	defer dbLock.Unlock()

	return out.CatchError(obj, dbConnection.Create(obj).Error)
}

//---
