package db2

// This file is automatically generated, manual editing is not recommended.

import (
	"encoding/json"
	"fmt"
	"time"

	"fyne.io/fyne/v2/data/binding"
	"github.com/lukx33/lwhelper"
	"github.com/lukx33/lwhelper/out"
	"gorm.io/gorm"
)

var tmpDNSProvider = lwhelper.ID()

type DNSProvider interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	ID() string
	Created() int64
	Updated() int64

	Azure_ClientID() string
	SetAzure_ClientID(value string) out.Info
	Azure_Email() string
	SetAzure_Email(value string) out.Info
	Azure_HOSTED_ZONE_NAME() string
	SetAzure_HOSTED_ZONE_NAME(value string) out.Info
	Azure_Key() string
	SetAzure_Key(value string) out.Info
	Azure_RESOURCE_GROUP_NAME() string
	SetAzure_RESOURCE_GROUP_NAME(value string) out.Info
	Azure_SUBSCRIPTION_ID() string
	SetAzure_SUBSCRIPTION_ID(value string) out.Info
	Azure_TenantID() string
	SetAzure_TenantID(value string) out.Info
	Cloudflare_Email() string
	SetCloudflare_Email(value string) out.Info
	Cloudflare_Key() string
	SetCloudflare_Key(value string) out.Info
	Enabled() bool
	SetEnabled(value bool) out.Info
	Name() string
	SetName(value string) out.Info
	Organization() Organization
	SetOrganization(value Organization) out.Info
	Variant() DNSProviderVariantT
	SetVariant(value DNSProviderVariantT) out.Info
	Delete() out.Info
}
type dNSProviderS struct {
	out.DontUseMeInfoS `gorm:"-"`

	IDC      string `gorm:"column:ID;primaryKey"`
	CreatedC int64  `gorm:"column:Created;autoCreateTime"`
	UpdatedC int64  `gorm:"column:Updated;autoUpdateTime"`

	Azure_ClientIDC            string              `gorm:"column:Azure_ClientID"`
	Azure_EmailC               string              `gorm:"column:Azure_Email"`
	Azure_HOSTED_ZONE_NAMEC    string              `gorm:"column:Azure_HOSTED_ZONE_NAME"`
	Azure_KeyC                 string              `gorm:"column:Azure_Key"`
	Azure_RESOURCE_GROUP_NAMEC string              `gorm:"column:Azure_RESOURCE_GROUP_NAME"`
	Azure_SUBSCRIPTION_IDC     string              `gorm:"column:Azure_SUBSCRIPTION_ID"`
	Azure_TenantIDC            string              `gorm:"column:Azure_TenantID"`
	Cloudflare_EmailC          string              `gorm:"column:Cloudflare_Email"`
	Cloudflare_KeyC            string              `gorm:"column:Cloudflare_Key"`
	EnabledC                   bool                `gorm:"column:Enabled"`
	NameC                      string              `gorm:"column:Name"`
	OrganizationC              string              `gorm:"column:Organization"`
	VariantC                   DNSProviderVariantT `gorm:"column:Variant"`
}

func (dNSProviderS) TableName() string {
	return "DNSProvider"
}

// ---

func (o *dNSProviderS) AfterFind(tx *gorm.DB) error {
	return nil
}

// ---

func (o *dNSProviderS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *dNSProviderS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

func (o *dNSProviderS) AddListener(l binding.DataListener) {
	fmt.Println("DNSProvider AddListener")
}

func (o *dNSProviderS) RemoveListener(l binding.DataListener) {
	fmt.Println("DNSProvider RemoveListener")
}

func (o *dNSProviderS) Delete() out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Where("ID = ?", o.IDC).Delete(&dNSProviderS{}).Error
	if err != nil {
		return out.New(err)
	}

	return out.NewSuccess()
}

func dNSProviderCreateOrUpdate(srcB []byte) {

	src := &dNSProviderS{}
	json.Unmarshal(srcB, src)
	id := src.IDC
	// src.InfoPrint()

	if id == "" {
		panic("cos tu jest nie tak")
	}

	srcMap := map[string]any{}
	json.Unmarshal(src.InfoJSON(), &srcMap)
	delete(srcMap, "trace")
	delete(srcMap, "result")
	delete(srcMap, "vars")
	delete(srcMap, "IDC")
	// out.PrintJSON(srcMap)

	dbLock.Lock()
	defer dbLock.Unlock()

	var exists bool
	if out.New(dbConnection.Model(&dNSProviderS{}).Select("count(*) > 0").
		Where("id = ?", id).Find(&exists).Error).NotValid() {
		return
	}
	if !exists {
		// new item, creating
		// fmt.Println("new item")
		out.New(dbConnection.Create(src).Error)
		return
	}

	// looking for changes
	// fmt.Println("changes")
	out.New(dbConnection.Model(&dNSProviderS{}).Where("ID = ?", id).Updates(srcMap).Error)
}

// ---
// ID

func (o *dNSProviderS) ID() string {
	if o == nil {
		return ""
	}
	return o.IDC
}

// ---
// Created

func (o *dNSProviderS) Created() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedC
}

// ---
// Updated

func (o *dNSProviderS) Updated() int64 {
	if o == nil {
		return 0
	}
	return o.UpdatedC
}

// ---
// Azure_ClientID

func (o *dNSProviderS) Azure_ClientID() string {
	if o == nil {
		return ""
	}
	return o.Azure_ClientIDC
}

func (o *dNSProviderS) SetAzure_ClientID(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_ClientIDC
	o.Azure_ClientIDC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Azure_ClientID", value).Error
	if err != nil {
		o.Azure_ClientIDC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_Email

func (o *dNSProviderS) Azure_Email() string {
	if o == nil {
		return ""
	}
	return o.Azure_EmailC
}

func (o *dNSProviderS) SetAzure_Email(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_EmailC
	o.Azure_EmailC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Azure_Email", value).Error
	if err != nil {
		o.Azure_EmailC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_HOSTED_ZONE_NAME

func (o *dNSProviderS) Azure_HOSTED_ZONE_NAME() string {
	if o == nil {
		return ""
	}
	return o.Azure_HOSTED_ZONE_NAMEC
}

func (o *dNSProviderS) SetAzure_HOSTED_ZONE_NAME(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_HOSTED_ZONE_NAMEC
	o.Azure_HOSTED_ZONE_NAMEC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Azure_HOSTED_ZONE_NAME", value).Error
	if err != nil {
		o.Azure_HOSTED_ZONE_NAMEC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_Key

func (o *dNSProviderS) Azure_Key() string {
	if o == nil {
		return ""
	}
	return o.Azure_KeyC
}

func (o *dNSProviderS) SetAzure_Key(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_KeyC
	o.Azure_KeyC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Azure_Key", value).Error
	if err != nil {
		o.Azure_KeyC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_RESOURCE_GROUP_NAME

func (o *dNSProviderS) Azure_RESOURCE_GROUP_NAME() string {
	if o == nil {
		return ""
	}
	return o.Azure_RESOURCE_GROUP_NAMEC
}

func (o *dNSProviderS) SetAzure_RESOURCE_GROUP_NAME(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_RESOURCE_GROUP_NAMEC
	o.Azure_RESOURCE_GROUP_NAMEC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Azure_RESOURCE_GROUP_NAME", value).Error
	if err != nil {
		o.Azure_RESOURCE_GROUP_NAMEC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_SUBSCRIPTION_ID

func (o *dNSProviderS) Azure_SUBSCRIPTION_ID() string {
	if o == nil {
		return ""
	}
	return o.Azure_SUBSCRIPTION_IDC
}

func (o *dNSProviderS) SetAzure_SUBSCRIPTION_ID(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_SUBSCRIPTION_IDC
	o.Azure_SUBSCRIPTION_IDC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Azure_SUBSCRIPTION_ID", value).Error
	if err != nil {
		o.Azure_SUBSCRIPTION_IDC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Azure_TenantID

func (o *dNSProviderS) Azure_TenantID() string {
	if o == nil {
		return ""
	}
	return o.Azure_TenantIDC
}

func (o *dNSProviderS) SetAzure_TenantID(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Azure_TenantIDC
	o.Azure_TenantIDC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Azure_TenantID", value).Error
	if err != nil {
		o.Azure_TenantIDC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Cloudflare_Email

func (o *dNSProviderS) Cloudflare_Email() string {
	if o == nil {
		return ""
	}
	return o.Cloudflare_EmailC
}

func (o *dNSProviderS) SetCloudflare_Email(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Cloudflare_EmailC
	o.Cloudflare_EmailC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Cloudflare_Email", value).Error
	if err != nil {
		o.Cloudflare_EmailC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Cloudflare_Key

func (o *dNSProviderS) Cloudflare_Key() string {
	if o == nil {
		return ""
	}
	return o.Cloudflare_KeyC
}

func (o *dNSProviderS) SetCloudflare_Key(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.Cloudflare_KeyC
	o.Cloudflare_KeyC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Cloudflare_Key", value).Error
	if err != nil {
		o.Cloudflare_KeyC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Enabled

func (o *dNSProviderS) Enabled() bool {
	if o == nil {
		return false
	}
	return o.EnabledC
}

func (o *dNSProviderS) SetEnabled(value bool) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.EnabledC
	o.EnabledC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Enabled", value).Error
	if err != nil {
		o.EnabledC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Name

func (o *dNSProviderS) Name() string {
	if o == nil {
		return ""
	}
	return o.NameC
}

func (o *dNSProviderS) SetName(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.NameC
	o.NameC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Name", value).Error
	if err != nil {
		o.NameC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Organization

func (o *dNSProviderS) Organization() Organization {
	if o == nil {
		return nil
	}
	return OrganizationGetByID(o.OrganizationC)
}

func (o *dNSProviderS) SetOrganization(value Organization) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.OrganizationC
	o.OrganizationC = value.ID()

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Organization", value.ID()).Error
	if err != nil {
		o.OrganizationC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Variant

func (o *dNSProviderS) Variant() DNSProviderVariantT {
	if o == nil {
		return 0
	}
	return o.VariantC
}

func (o *dNSProviderS) SetVariant(value DNSProviderVariantT) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.VariantC
	o.VariantC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&dNSProviderS{}).Where("ID = ?", o.IDC).Update("Variant", value).Error
	if err != nil {
		o.VariantC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ----------------------------------------------------- table list:

type dNSProviderList interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	Length() int
	First() DNSProvider
	GetByID(id string) DNSProvider
	Iter() []DNSProvider
	Refresh() out.Info
	SetWhere(where string) out.Info
	SetOrder(order string) out.Info
	SetOffset(offset int) out.Info
	SetLimit(limit int) out.Info

	AddListener(dl binding.DataListener)
	RemoveListener(dl binding.DataListener)
	GetItem(index int) (binding.DataItem, error)
}

type dNSProviderListS struct {
	out.DontUseMeInfoS

	query        req_listQueryS
	M            map[string]*dNSProviderS
	IDs          []string
	IDtoIdx      map[string]int
	dataListener map[binding.DataListener]bool
}

//---

func (o *dNSProviderListS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *dNSProviderListS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

func (o *dNSProviderListS) AddListener(dl binding.DataListener) {
	// fmt.Println("DNSProviderList AddListener")
	if o.dataListener == nil {
		o.dataListener = map[binding.DataListener]bool{}
	}
	o.dataListener[dl] = true
}

func (o *dNSProviderListS) RemoveListener(dl binding.DataListener) {
	// fmt.Println("DNSProviderList RemoveListener")
	delete(o.dataListener, dl)
}

func (o *dNSProviderListS) GetItem(index int) (binding.DataItem, error) {
	// fmt.Println("DNSProviderList GetItem")
	return o.M[o.IDs[index]], nil
}

func (o *dNSProviderListS) Length() int {
	// fmt.Println("DNSProviderList Length")
	return len(o.IDs)
}

func (o *dNSProviderListS) SetWhere(where string) out.Info {
	o.query = req_listQueryS{
		Where: where,
	}
	return o.Refresh()
}

func (o *dNSProviderListS) SetOrder(order string) out.Info {
	o.query = req_listQueryS{
		Order: order,
	}
	return o.Refresh()
}

func (o *dNSProviderListS) SetOffset(offset int) out.Info {
	o.query = req_listQueryS{
		Offset: offset,
	}
	return o.Refresh()
}

func (o *dNSProviderListS) SetLimit(limit int) out.Info {
	o.query = req_listQueryS{
		Limit: limit,
	}
	return o.Refresh()
}

//---

func DNSProviderList(where, order string, offset, limit int) dNSProviderList {

	response := &dNSProviderListS{
		query: req_listQueryS{
			Where:  where,
			Order:  order,
			Offset: offset,
			Limit:  limit,
		},
	}

	if where == "nil" {
		return response
	}

	response.Refresh()
	return response
}

func (o *dNSProviderListS) Refresh() out.Info {

	if o.query.Where == "nil" {
		return o
	}

	res := &dNSProviderListS{
		query:        o.query,
		IDs:          []string{},
		IDtoIdx:      map[string]int{},
		M:            map[string]*dNSProviderS{},
		dataListener: o.dataListener,
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	st := dbConnection.Model(&dNSProviderS{})
	if o.query.Where != "" {
		st.Where(o.query.Where)
	}
	if o.query.Order == "" {
		o.query.Order = "Created"
	}
	if o.query.Limit == 0 {
		o.query.Limit = 30
	}

	responseList := []*dNSProviderS{}
	if out.CatchError(res,
		st.Order(o.query.Order).Offset(o.query.Offset).Limit(o.query.Limit).Find(&responseList).Error,
	).NotValid() {
		return res
	}
	// out.PrintJSON(responseList)

	for idx, entry := range responseList {
		res.IDs = append(res.IDs, entry.IDC)
		res.IDtoIdx[entry.IDC] = idx
		res.M[entry.IDC] = entry
	}

	out.CatchError(res, nil)
	*o = *res

	for dl := range o.dataListener {
		// fmt.Println(">>>>>>>>>>>>>>>>>> dataListener", dl)
		dl.DataChanged()
	}
	return res
}

func (o *dNSProviderListS) First() DNSProvider {
	for _, obj := range o.M {
		return out.CatchError(obj, nil)
	}

	res := &dNSProviderS{}
	res.InfoAddTrace(out.NotFound, "", 0)
	return res
}

func (o *dNSProviderListS) GetByID(id string) DNSProvider {
	res, exist := o.M[id]
	if !exist {
		res.InfoAddTrace(out.NotFound, "", 0)
		return res
	}
	return out.CatchError(res, nil)
}

func (o *dNSProviderListS) Iter() []DNSProvider {

	if o.NotValid() {
		return nil
	}

	res := []DNSProvider{}
	for _, id := range o.IDs {
		res = append(res, out.CatchError(o.M[id], nil))
	}
	return res
}

// ---

func DNSProviderGetByID(key string) DNSProvider {

	res := &dNSProviderS{}
	if key == "" {
		res.InfoAddTrace(out.NotFound, "", 0)
		return res
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	out.CatchError(res, dbConnection.Where("ID = ?", key).First(res).Error)

	if res.NotValid() && res.InfoLastTrace().Message == "record not found" {
		res.Result = out.NotFound
	}

	return res
}

//---

func DNSProviderCreate(
	Name string,
	Organization Organization,
	Variant DNSProviderVariantT,
) DNSProvider {

	// TODO: Input data validation

	now := time.Now()
	obj := &dNSProviderS{
		IDC:           lwhelper.ID(),
		CreatedC:      now.Unix(),
		UpdatedC:      now.Unix(),
		NameC:         Name,
		OrganizationC: Organization.ID(),
		VariantC:      Variant,
	}

	obj.EnabledC = true

	// Saving data to the database
	dbLock.Lock()
	defer dbLock.Unlock()

	return out.CatchError(obj, dbConnection.Create(obj).Error)
}

//---
