package db2

// This file is automatically generated, manual editing is not recommended.

import (
	"encoding/json"
	"fmt"
	"time"

	"fyne.io/fyne/v2/data/binding"
	"github.com/lukx33/lwhelper"
	"github.com/lukx33/lwhelper/out"
	"gorm.io/gorm"
)

var tmpNotificationProvider = lwhelper.ID()

type NotificationProvider interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	ID() string
	Created() int64
	Updated() int64

	Enabled() bool
	SetEnabled(value bool) out.Info
	Name() string
	SetName(value string) out.Info
	Organization() Organization
	SetOrganization(value Organization) out.Info
	SMTP_Host() string
	SetSMTP_Host(value string) out.Info
	SMTP_Login() string
	SetSMTP_Login(value string) out.Info
	SMTP_Password() string
	SetSMTP_Password(value string) out.Info
	SMTP_Port() int64
	SetSMTP_Port(value int64) out.Info
	SMTP_SenderEmail() string
	SetSMTP_SenderEmail(value string) out.Info
	SMTP_SenderName() string
	SetSMTP_SenderName(value string) out.Info
	Variant() NotificationProviderVariantT
	SetVariant(value NotificationProviderVariantT) out.Info
	Delete() out.Info
}
type notificationProviderS struct {
	out.DontUseMeInfoS `gorm:"-"`

	IDC      string `gorm:"column:ID;primaryKey"`
	CreatedC int64  `gorm:"column:Created;autoCreateTime"`
	UpdatedC int64  `gorm:"column:Updated;autoUpdateTime"`

	EnabledC          bool                         `gorm:"column:Enabled"`
	NameC             string                       `gorm:"column:Name"`
	OrganizationC     string                       `gorm:"column:Organization"`
	SMTP_HostC        string                       `gorm:"column:SMTP_Host"`
	SMTP_LoginC       string                       `gorm:"column:SMTP_Login"`
	SMTP_PasswordC    string                       `gorm:"column:SMTP_Password"`
	SMTP_PortC        int64                        `gorm:"column:SMTP_Port"`
	SMTP_SenderEmailC string                       `gorm:"column:SMTP_SenderEmail"`
	SMTP_SenderNameC  string                       `gorm:"column:SMTP_SenderName"`
	VariantC          NotificationProviderVariantT `gorm:"column:Variant"`
}

func (notificationProviderS) TableName() string {
	return "NotificationProvider"
}

// ---

func (o *notificationProviderS) AfterFind(tx *gorm.DB) error {
	return nil
}

// ---

func (o *notificationProviderS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *notificationProviderS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

func (o *notificationProviderS) AddListener(l binding.DataListener) {
	fmt.Println("NotificationProvider AddListener")
}

func (o *notificationProviderS) RemoveListener(l binding.DataListener) {
	fmt.Println("NotificationProvider RemoveListener")
}

func (o *notificationProviderS) Delete() out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Where("ID = ?", o.IDC).Delete(&notificationProviderS{}).Error
	if err != nil {
		return out.New(err)
	}

	return out.NewSuccess()
}

func notificationProviderCreateOrUpdate(srcB []byte) {

	src := &notificationProviderS{}
	json.Unmarshal(srcB, src)
	id := src.IDC
	// src.InfoPrint()

	if id == "" {
		panic("cos tu jest nie tak")
	}

	srcMap := map[string]any{}
	json.Unmarshal(src.InfoJSON(), &srcMap)
	delete(srcMap, "trace")
	delete(srcMap, "result")
	delete(srcMap, "vars")
	delete(srcMap, "IDC")
	// out.PrintJSON(srcMap)

	dbLock.Lock()
	defer dbLock.Unlock()

	var exists bool
	if out.New(dbConnection.Model(&notificationProviderS{}).Select("count(*) > 0").
		Where("id = ?", id).Find(&exists).Error).NotValid() {
		return
	}
	if !exists {
		// new item, creating
		// fmt.Println("new item")
		out.New(dbConnection.Create(src).Error)
		return
	}

	// looking for changes
	// fmt.Println("changes")
	out.New(dbConnection.Model(&notificationProviderS{}).Where("ID = ?", id).Updates(srcMap).Error)
}

// ---
// ID

func (o *notificationProviderS) ID() string {
	if o == nil {
		return ""
	}
	return o.IDC
}

// ---
// Created

func (o *notificationProviderS) Created() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedC
}

// ---
// Updated

func (o *notificationProviderS) Updated() int64 {
	if o == nil {
		return 0
	}
	return o.UpdatedC
}

// ---
// Enabled

func (o *notificationProviderS) Enabled() bool {
	if o == nil {
		return false
	}
	return o.EnabledC
}

func (o *notificationProviderS) SetEnabled(value bool) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.EnabledC
	o.EnabledC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("Enabled", value).Error
	if err != nil {
		o.EnabledC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Name

func (o *notificationProviderS) Name() string {
	if o == nil {
		return ""
	}
	return o.NameC
}

func (o *notificationProviderS) SetName(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.NameC
	o.NameC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("Name", value).Error
	if err != nil {
		o.NameC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Organization

func (o *notificationProviderS) Organization() Organization {
	if o == nil {
		return nil
	}
	return OrganizationGetByID(o.OrganizationC)
}

func (o *notificationProviderS) SetOrganization(value Organization) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.OrganizationC
	o.OrganizationC = value.ID()

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("Organization", value.ID()).Error
	if err != nil {
		o.OrganizationC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// SMTP_Host

func (o *notificationProviderS) SMTP_Host() string {
	if o == nil {
		return ""
	}
	return o.SMTP_HostC
}

func (o *notificationProviderS) SetSMTP_Host(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.SMTP_HostC
	o.SMTP_HostC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("SMTP_Host", value).Error
	if err != nil {
		o.SMTP_HostC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// SMTP_Login

func (o *notificationProviderS) SMTP_Login() string {
	if o == nil {
		return ""
	}
	return o.SMTP_LoginC
}

func (o *notificationProviderS) SetSMTP_Login(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.SMTP_LoginC
	o.SMTP_LoginC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("SMTP_Login", value).Error
	if err != nil {
		o.SMTP_LoginC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// SMTP_Password

func (o *notificationProviderS) SMTP_Password() string {
	if o == nil {
		return ""
	}
	return o.SMTP_PasswordC
}

func (o *notificationProviderS) SetSMTP_Password(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.SMTP_PasswordC
	o.SMTP_PasswordC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("SMTP_Password", value).Error
	if err != nil {
		o.SMTP_PasswordC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// SMTP_Port

func (o *notificationProviderS) SMTP_Port() int64 {
	if o == nil {
		return 0
	}
	return o.SMTP_PortC
}

func (o *notificationProviderS) SetSMTP_Port(value int64) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.SMTP_PortC
	o.SMTP_PortC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("SMTP_Port", value).Error
	if err != nil {
		o.SMTP_PortC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// SMTP_SenderEmail

func (o *notificationProviderS) SMTP_SenderEmail() string {
	if o == nil {
		return ""
	}
	return o.SMTP_SenderEmailC
}

func (o *notificationProviderS) SetSMTP_SenderEmail(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.SMTP_SenderEmailC
	o.SMTP_SenderEmailC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("SMTP_SenderEmail", value).Error
	if err != nil {
		o.SMTP_SenderEmailC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// SMTP_SenderName

func (o *notificationProviderS) SMTP_SenderName() string {
	if o == nil {
		return ""
	}
	return o.SMTP_SenderNameC
}

func (o *notificationProviderS) SetSMTP_SenderName(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.SMTP_SenderNameC
	o.SMTP_SenderNameC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("SMTP_SenderName", value).Error
	if err != nil {
		o.SMTP_SenderNameC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Variant

func (o *notificationProviderS) Variant() NotificationProviderVariantT {
	if o == nil {
		return 0
	}
	return o.VariantC
}

func (o *notificationProviderS) SetVariant(value NotificationProviderVariantT) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	// TODO: if current value == new value, then there is no point in changing anything

	oldValue := o.VariantC
	o.VariantC = value

	dbLock.Lock()
	defer dbLock.Unlock()

	err := dbConnection.Model(&notificationProviderS{}).Where("ID = ?", o.IDC).Update("Variant", value).Error
	if err != nil {
		o.VariantC = oldValue
		return out.New(err)
	}

	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ----------------------------------------------------- table list:

type notificationProviderList interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	Length() int
	First() NotificationProvider
	GetByID(id string) NotificationProvider
	Iter() []NotificationProvider
	Refresh() out.Info
	SetWhere(where string) out.Info
	SetOrder(order string) out.Info
	SetOffset(offset int) out.Info
	SetLimit(limit int) out.Info

	AddListener(dl binding.DataListener)
	RemoveListener(dl binding.DataListener)
	GetItem(index int) (binding.DataItem, error)
}

type notificationProviderListS struct {
	out.DontUseMeInfoS

	query        req_listQueryS
	M            map[string]*notificationProviderS
	IDs          []string
	IDtoIdx      map[string]int
	dataListener map[binding.DataListener]bool
}

//---

func (o *notificationProviderListS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *notificationProviderListS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

func (o *notificationProviderListS) AddListener(dl binding.DataListener) {
	// fmt.Println("NotificationProviderList AddListener")
	if o.dataListener == nil {
		o.dataListener = map[binding.DataListener]bool{}
	}
	o.dataListener[dl] = true
}

func (o *notificationProviderListS) RemoveListener(dl binding.DataListener) {
	// fmt.Println("NotificationProviderList RemoveListener")
	delete(o.dataListener, dl)
}

func (o *notificationProviderListS) GetItem(index int) (binding.DataItem, error) {
	// fmt.Println("NotificationProviderList GetItem")
	return o.M[o.IDs[index]], nil
}

func (o *notificationProviderListS) Length() int {
	// fmt.Println("NotificationProviderList Length")
	return len(o.IDs)
}

func (o *notificationProviderListS) SetWhere(where string) out.Info {
	o.query = req_listQueryS{
		Where: where,
	}
	return o.Refresh()
}

func (o *notificationProviderListS) SetOrder(order string) out.Info {
	o.query = req_listQueryS{
		Order: order,
	}
	return o.Refresh()
}

func (o *notificationProviderListS) SetOffset(offset int) out.Info {
	o.query = req_listQueryS{
		Offset: offset,
	}
	return o.Refresh()
}

func (o *notificationProviderListS) SetLimit(limit int) out.Info {
	o.query = req_listQueryS{
		Limit: limit,
	}
	return o.Refresh()
}

//---

func NotificationProviderList(where, order string, offset, limit int) notificationProviderList {

	response := &notificationProviderListS{
		query: req_listQueryS{
			Where:  where,
			Order:  order,
			Offset: offset,
			Limit:  limit,
		},
	}

	if where == "nil" {
		return response
	}

	response.Refresh()
	return response
}

func (o *notificationProviderListS) Refresh() out.Info {

	if o.query.Where == "nil" {
		return o
	}

	res := &notificationProviderListS{
		query:        o.query,
		IDs:          []string{},
		IDtoIdx:      map[string]int{},
		M:            map[string]*notificationProviderS{},
		dataListener: o.dataListener,
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	st := dbConnection.Model(&notificationProviderS{})
	if o.query.Where != "" {
		st.Where(o.query.Where)
	}
	if o.query.Order == "" {
		o.query.Order = "Created"
	}
	if o.query.Limit == 0 {
		o.query.Limit = 30
	}

	responseList := []*notificationProviderS{}
	if out.CatchError(res,
		st.Order(o.query.Order).Offset(o.query.Offset).Limit(o.query.Limit).Find(&responseList).Error,
	).NotValid() {
		return res
	}
	// out.PrintJSON(responseList)

	for idx, entry := range responseList {
		res.IDs = append(res.IDs, entry.IDC)
		res.IDtoIdx[entry.IDC] = idx
		res.M[entry.IDC] = entry
	}

	out.CatchError(res, nil)
	*o = *res

	for dl := range o.dataListener {
		// fmt.Println(">>>>>>>>>>>>>>>>>> dataListener", dl)
		dl.DataChanged()
	}
	return res
}

func (o *notificationProviderListS) First() NotificationProvider {
	for _, obj := range o.M {
		return out.CatchError(obj, nil)
	}

	res := &notificationProviderS{}
	res.InfoAddTrace(out.NotFound, "", 0)
	return res
}

func (o *notificationProviderListS) GetByID(id string) NotificationProvider {
	res, exist := o.M[id]
	if !exist {
		res.InfoAddTrace(out.NotFound, "", 0)
		return res
	}
	return out.CatchError(res, nil)
}

func (o *notificationProviderListS) Iter() []NotificationProvider {

	if o.NotValid() {
		return nil
	}

	res := []NotificationProvider{}
	for _, id := range o.IDs {
		res = append(res, out.CatchError(o.M[id], nil))
	}
	return res
}

// ---

func NotificationProviderGetByID(key string) NotificationProvider {

	res := &notificationProviderS{}
	if key == "" {
		res.InfoAddTrace(out.NotFound, "", 0)
		return res
	}

	dbLock.Lock()
	defer dbLock.Unlock()

	out.CatchError(res, dbConnection.Where("ID = ?", key).First(res).Error)

	if res.NotValid() && res.InfoLastTrace().Message == "record not found" {
		res.Result = out.NotFound
	}

	return res
}

//---

func NotificationProviderCreate(
	Name string,
	Organization Organization,
	Variant NotificationProviderVariantT,
) NotificationProvider {

	// TODO: Input data validation

	now := time.Now()
	obj := &notificationProviderS{
		IDC:           lwhelper.ID(),
		CreatedC:      now.Unix(),
		UpdatedC:      now.Unix(),
		NameC:         Name,
		OrganizationC: Organization.ID(),
		VariantC:      Variant,
	}

	obj.EnabledC = true

	// Saving data to the database
	dbLock.Lock()
	defer dbLock.Unlock()

	return out.CatchError(obj, dbConnection.Create(obj).Error)
}

//---
