package fp

// This file is automatically generated, manual editing is not recommended.

type InstallationStatusT uint16

const (
	InstallationStatus_suspended InstallationStatusT = 1
	InstallationStatus_new       InstallationStatusT = 2
	InstallationStatus_deploying InstallationStatusT = 3
	InstallationStatus_error     InstallationStatusT = 4
	InstallationStatus_ready     InstallationStatusT = 5
	InstallationStatus_offline   InstallationStatusT = 6
)

var translationMapEN_InstallationStatus = map[InstallationStatusT]string{
	1: "suspended",
	2: "new",
	3: "deploying",
	4: "error",
	5: "ready",
	6: "offline",
}

func (o InstallationStatusT) EN() string { return translationMapEN_InstallationStatus[o] }

var translationMapPL_InstallationStatus = map[InstallationStatusT]string{
	1: "zatrzymana",
	2: "nowa",
	3: "wdrażanie",
	4: "błąd",
	5: "sprawna",
	6: "offline",
}

func (o InstallationStatusT) PL() string { return translationMapPL_InstallationStatus[o] }
