package fp

// This file is automatically generated, manual editing is not recommended.

type NotificationProviderVariantT uint16

const (
	NotificationProviderVariant_SMTP NotificationProviderVariantT = 1
	NotificationProviderVariant_SMS  NotificationProviderVariantT = 2
)

var translationMapEN_NotificationProviderVariant = map[NotificationProviderVariantT]string{
	1: "SMTP",
	2: "SMS",
}

func (o NotificationProviderVariantT) EN() string {
	return translationMapEN_NotificationProviderVariant[o]
}

var translationMapPL_NotificationProviderVariant = map[NotificationProviderVariantT]string{
	1: "SMTP",
	2: "SMS",
}

func (o NotificationProviderVariantT) PL() string {
	return translationMapPL_NotificationProviderVariant[o]
}
