package fp

// This file is automatically generated, manual editing is not recommended.

type UserStatusT uint16

const (
	UserStatus_new     UserStatusT = 1
	UserStatus_active  UserStatusT = 2
	UserStatus_blocked UserStatusT = 3
)

var translationMapEN_UserStatus = map[UserStatusT]string{
	1: "new",
	2: "active",
	3: "blocked",
}

func (o UserStatusT) EN() string { return translationMapEN_UserStatus[o] }

var translationMapPL_UserStatus = map[UserStatusT]string{
	1: "nowy",
	2: "aktywny",
	3: "zablokowany",
}

func (o UserStatusT) PL() string { return translationMapPL_UserStatus[o] }
