package fp

// This file is automatically generated, manual editing is not recommended.

import (
	"encoding/json"
	"fmt"
	"time"

	"fyne.io/fyne/v2/data/binding"
	"github.com/lukx33/lwhelper"
	"github.com/lukx33/lwhelper/out"
)

var tmpImageBuilder = lwhelper.ID()

type ImageBuilder interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	ID() string
	Created() int64
	Updated() int64

	Enabled() bool
	SetEnabled(value bool) out.Info
	Name() string
	SetName(value string) out.Info
	Organization() Organization
	SetOrganization(value Organization) out.Info
	TimoniExternal_Token() string
	SetTimoniExternal_Token(value string) out.Info
	TimoniExternal_URL() string
	SetTimoniExternal_URL(value string) out.Info
	Timoni_MaxNumberOfConcurrentBuilds() int64
	SetTimoni_MaxNumberOfConcurrentBuilds(value int64) out.Info
	Timoni_Token() string
	SetTimoni_Token(value string) out.Info
	Variant() ImageBuilderVariantT
	SetVariant(value ImageBuilderVariantT) out.Info
	Delete() out.Info
}
type imageBuilderS struct {
	out.DontUseMeInfoS

	IDC      string
	CreatedC int64
	UpdatedC int64

	EnabledC                            bool
	NameC                               string
	OrganizationC                       string
	TimoniExternal_TokenC               string
	TimoniExternal_URLC                 string
	Timoni_MaxNumberOfConcurrentBuildsC int64
	Timoni_TokenC                       string
	VariantC                            ImageBuilderVariantT
}

func (o *imageBuilderS) dataMapEN() map[string]string {
	return map[string]string{
		"ID":                                 o.IDC,
		"Created":                            fmt.Sprint(o.CreatedC),
		"Updated":                            fmt.Sprint(o.UpdatedC),
		"Enabled":                            fmt.Sprint(o.EnabledC),
		"Name":                               o.NameC,
		"Organization":                       o.OrganizationC,
		"TimoniExternal_Token":               o.TimoniExternal_TokenC,
		"TimoniExternal_URL":                 o.TimoniExternal_URLC,
		"Timoni_MaxNumberOfConcurrentBuilds": fmt.Sprint(o.Timoni_MaxNumberOfConcurrentBuildsC),
		"Timoni_Token":                       o.Timoni_TokenC,
		"Variant":                            o.VariantC.EN(),
	}
}

// ---

func (o *imageBuilderS) AddListener(l binding.DataListener) {
	fmt.Println("ImageBuilder AddListener")
}

func (o *imageBuilderS) RemoveListener(l binding.DataListener) {
	fmt.Println("ImageBuilder RemoveListener")
}

// ---

func (o *imageBuilderS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *imageBuilderS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

// ---
// ID

func (o *imageBuilderS) ID() string {
	if o == nil {
		return ""
	}
	return o.IDC
}

// ---
// Created

func (o *imageBuilderS) Created() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedC
}

// ---
// Updated

func (o *imageBuilderS) Updated() int64 {
	if o == nil {
		return 0
	}
	return o.UpdatedC
}

// ---
// Enabled

func (o *imageBuilderS) Enabled() bool {
	return o.EnabledC
}

func (o *imageBuilderS) SetEnabled(value bool) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderSetEnabled",
		req_setBoolS{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.EnabledC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Name

func (o *imageBuilderS) Name() string {
	return o.NameC
}

func (o *imageBuilderS) SetName(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderSetName",
		req_setStringS{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.NameC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Organization

func (o *imageBuilderS) Organization() Organization {
	return OrganizationGetByID(o.OrganizationC)
}

func (o *imageBuilderS) SetOrganization(value Organization) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderSetOrganization",
		req_setRelationS{
			ID:     o.IDC,
			NewKey: value.ID(),
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.OrganizationC = value.ID()
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// TimoniExternal_Token

func (o *imageBuilderS) TimoniExternal_Token() string {
	return o.TimoniExternal_TokenC
}

func (o *imageBuilderS) SetTimoniExternal_Token(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderSetTimoniExternal_Token",
		req_setStringS{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.TimoniExternal_TokenC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// TimoniExternal_URL

func (o *imageBuilderS) TimoniExternal_URL() string {
	return o.TimoniExternal_URLC
}

func (o *imageBuilderS) SetTimoniExternal_URL(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderSetTimoniExternal_URL",
		req_setStringS{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.TimoniExternal_URLC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Timoni_MaxNumberOfConcurrentBuilds

func (o *imageBuilderS) Timoni_MaxNumberOfConcurrentBuilds() int64 {
	return o.Timoni_MaxNumberOfConcurrentBuildsC
}

func (o *imageBuilderS) SetTimoni_MaxNumberOfConcurrentBuilds(value int64) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderSetTimoni_MaxNumberOfConcurrentBuilds",
		req_setInt64S{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.Timoni_MaxNumberOfConcurrentBuildsC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Timoni_Token

func (o *imageBuilderS) Timoni_Token() string {
	return o.Timoni_TokenC
}

func (o *imageBuilderS) SetTimoni_Token(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderSetTimoni_Token",
		req_setStringS{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.Timoni_TokenC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Variant

func (o *imageBuilderS) Variant() ImageBuilderVariantT {
	return o.VariantC
}

func (o *imageBuilderS) SetVariant(value ImageBuilderVariantT) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderSetVariant",
		req_setUInt16S{
			ID:       o.IDC,
			NewValue: uint16(value),
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.VariantC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---

func ImageBuilderGetByID(ID string) ImageBuilder {

	response := &imageBuilderS{}
	client.call(
		"ImageBuilderGetByID",
		req_oneS{
			ID: ID,
		},
		response,
	)

	return response
}

// ---

func (o *imageBuilderS) Delete() out.Info {

	response := new(out.DontUseMeInfoS)
	client.call(
		"ImageBuilderDelete",
		req_oneS{
			ID: o.ID(),
		},
		response,
	)

	return response
}

// ---

type req_ImageBuilderCreateS struct {
	Name         string
	Organization string
	Variant      ImageBuilderVariantT
}

func ImageBuilderCreate(
	Name string,
	Organization Organization,
	Variant ImageBuilderVariantT,

) ImageBuilder {

	response := &imageBuilderS{}
	client.call(
		"ImageBuilderCreate",
		req_ImageBuilderCreateS{
			Name:         Name,
			Organization: Organization.ID(),
			Variant:      Variant,
		},
		response,
	)
	return response
}

// ----------------------------------------------------- table list:

type imageBuilderList interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	Length() int
	First() ImageBuilder
	GetByID(id string) ImageBuilder
	Iter() []ImageBuilder
	Refresh() out.Info
	SetWhere(where string) out.Info
	SetOrder(order string) out.Info
	SetOffset(offset int) out.Info
	SetLimit(limit int) out.Info

	AddListener(dl binding.DataListener)
	RemoveListener(dl binding.DataListener)
	GetItem(index int) (binding.DataItem, error)
}

type imageBuilderListS struct {
	out.DontUseMeInfoS

	query   req_listQueryS
	IDs     []string
	IDtoIdx map[string]int
	M       map[string]*imageBuilderS

	dataListener map[binding.DataListener]bool
}

func (o *imageBuilderListS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *imageBuilderListS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

func (o *imageBuilderListS) AddListener(dl binding.DataListener) {
	// fmt.Println("ImageBuilderList AddListener")
	if o.dataListener == nil {
		o.dataListener = map[binding.DataListener]bool{}
	}
	o.dataListener[dl] = true
}

func (o *imageBuilderListS) RemoveListener(dl binding.DataListener) {
	// fmt.Println("ImageBuilderList RemoveListener")
	delete(o.dataListener, dl)
}

func (o *imageBuilderListS) GetItem(index int) (binding.DataItem, error) {
	// fmt.Println("ImageBuilderList GetItem")
	return o.M[o.IDs[index]], nil
}

func (o *imageBuilderListS) Length() int {
	// fmt.Println("ImageBuilderList Length")
	return len(o.IDs)
}

//---

func ImageBuilderList(where, order string, offset, limit int) imageBuilderList {

	response := &imageBuilderListS{
		query: req_listQueryS{
			Where:  where,
			Order:  order,
			Offset: offset,
			Limit:  limit,
		},
	}

	if where == "nil" {
		return response
	}

	response.Refresh()
	return response
}

func (o *imageBuilderListS) SetWhere(where string) out.Info {
	o.query = req_listQueryS{
		Where: where,
	}
	return o.Refresh()
}

func (o *imageBuilderListS) SetOrder(order string) out.Info {
	o.query = req_listQueryS{
		Order: order,
	}
	return o.Refresh()
}

func (o *imageBuilderListS) SetOffset(offset int) out.Info {
	o.query = req_listQueryS{
		Offset: offset,
	}
	return o.Refresh()
}

func (o *imageBuilderListS) SetLimit(limit int) out.Info {
	o.query = req_listQueryS{
		Limit: limit,
	}
	return o.Refresh()
}

func (o *imageBuilderListS) First() ImageBuilder {
	for _, obj := range o.M {
		return out.CatchError(obj, nil)
	}

	res := &imageBuilderS{}
	res.InfoAddTrace(out.NotFound, "", 0)
	return res
}

func (o *imageBuilderListS) Iter() []ImageBuilder {

	if o.NotValid() {
		return nil
	}

	res := []ImageBuilder{}
	for _, id := range o.IDs {
		res = append(res, out.CatchError(o.M[id], nil))
	}
	return res
}

func (o *imageBuilderListS) Refresh() out.Info {

	if o.query.Where == "nil" {
		return o
	}

	response := &imageBuilderListS{
		query:        o.query,
		IDs:          []string{},
		IDtoIdx:      map[string]int{},
		M:            map[string]*imageBuilderS{},
		dataListener: o.dataListener,
	}

	client.call(
		"ImageBuilderList",
		o.query,
		response,
	)
	*o = *response

	for dl := range o.dataListener {
		// fmt.Println(">>>>>>>>>>>>>>>>>> dataListener", dl)
		dl.DataChanged()
	}
	return o
}

func (o *imageBuilderListS) GetByID(id string) ImageBuilder {
	return out.CatchError(o.M[id], nil)
}

//---

func (o *imageBuilderListS) GetByName(name string) ImageBuilder {

	for _, obj := range o.M {
		if obj.NameC == name {
			return out.CatchError(obj, nil)
		}
	}

	res := &imageBuilderS{}
	res.InfoAddTrace(out.NotFound, "", 0)
	return res
}
