package fp

// This file is automatically generated, manual editing is not recommended.

import (
	"encoding/json"
	"fmt"
	"time"

	"fyne.io/fyne/v2/data/binding"
	"github.com/lukx33/lwhelper"
	"github.com/lukx33/lwhelper/out"
)

var tmpKubeProvider = lwhelper.ID()

type KubeProvider interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	ID() string
	Created() int64
	Updated() int64

	Enabled() bool
	SetEnabled(value bool) out.Info
	ExistingCluster_ConfigContent() string
	SetExistingCluster_ConfigContent(value string) out.Info
	Name() string
	SetName(value string) out.Info
	Organization() Organization
	SetOrganization(value Organization) out.Info
	Variant() KubeProviderVariantT
	SetVariant(value KubeProviderVariantT) out.Info
	Delete() out.Info
}
type kubeProviderS struct {
	out.DontUseMeInfoS

	IDC      string
	CreatedC int64
	UpdatedC int64

	EnabledC                       bool
	ExistingCluster_ConfigContentC string
	NameC                          string
	OrganizationC                  string
	VariantC                       KubeProviderVariantT
}

func (o *kubeProviderS) dataMapEN() map[string]string {
	return map[string]string{
		"ID":                            o.IDC,
		"Created":                       fmt.Sprint(o.CreatedC),
		"Updated":                       fmt.Sprint(o.UpdatedC),
		"Enabled":                       fmt.Sprint(o.EnabledC),
		"ExistingCluster_ConfigContent": o.ExistingCluster_ConfigContentC,
		"Name":                          o.NameC,
		"Organization":                  o.OrganizationC,
		"Variant":                       o.VariantC.EN(),
	}
}

// ---

func (o *kubeProviderS) AddListener(l binding.DataListener) {
	fmt.Println("KubeProvider AddListener")
}

func (o *kubeProviderS) RemoveListener(l binding.DataListener) {
	fmt.Println("KubeProvider RemoveListener")
}

// ---

func (o *kubeProviderS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *kubeProviderS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

// ---
// ID

func (o *kubeProviderS) ID() string {
	if o == nil {
		return ""
	}
	return o.IDC
}

// ---
// Created

func (o *kubeProviderS) Created() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedC
}

// ---
// Updated

func (o *kubeProviderS) Updated() int64 {
	if o == nil {
		return 0
	}
	return o.UpdatedC
}

// ---
// Enabled

func (o *kubeProviderS) Enabled() bool {
	return o.EnabledC
}

func (o *kubeProviderS) SetEnabled(value bool) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"KubeProviderSetEnabled",
		req_setBoolS{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.EnabledC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// ExistingCluster_ConfigContent

func (o *kubeProviderS) ExistingCluster_ConfigContent() string {
	return o.ExistingCluster_ConfigContentC
}

func (o *kubeProviderS) SetExistingCluster_ConfigContent(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"KubeProviderSetExistingCluster_ConfigContent",
		req_setStringS{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.ExistingCluster_ConfigContentC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Name

func (o *kubeProviderS) Name() string {
	return o.NameC
}

func (o *kubeProviderS) SetName(value string) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"KubeProviderSetName",
		req_setStringS{
			ID:       o.IDC,
			NewValue: value,
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.NameC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Organization

func (o *kubeProviderS) Organization() Organization {
	return OrganizationGetByID(o.OrganizationC)
}

func (o *kubeProviderS) SetOrganization(value Organization) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"KubeProviderSetOrganization",
		req_setRelationS{
			ID:     o.IDC,
			NewKey: value.ID(),
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.OrganizationC = value.ID()
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---
// Variant

func (o *kubeProviderS) Variant() KubeProviderVariantT {
	return o.VariantC
}

func (o *kubeProviderS) SetVariant(value KubeProviderVariantT) out.Info {

	if o == nil {
		return out.NewErrorMsg("object is nil")
	}
	if o.NotValid() {
		return out.NewErrorMsg("object is not valid")
	}

	// TODO: validation

	response := new(out.DontUseMeInfoS)
	client.call(
		"KubeProviderSetVariant",
		req_setUInt16S{
			ID:       o.IDC,
			NewValue: uint16(value),
		},
		response,
	)
	if response.NotValid() {
		return response
	}

	o.VariantC = value
	o.UpdatedC = time.Now().Unix()
	return out.NewSuccess()
}

// ---

func KubeProviderGetByID(ID string) KubeProvider {

	response := &kubeProviderS{}
	client.call(
		"KubeProviderGetByID",
		req_oneS{
			ID: ID,
		},
		response,
	)

	return response
}

// ---

func (o *kubeProviderS) Delete() out.Info {

	response := new(out.DontUseMeInfoS)
	client.call(
		"KubeProviderDelete",
		req_oneS{
			ID: o.ID(),
		},
		response,
	)

	return response
}

// ---

type req_KubeProviderCreateS struct {
	ExistingCluster_ConfigContent string
	Name                          string
	Organization                  string
	Variant                       KubeProviderVariantT
}

func KubeProviderCreate(
	ExistingCluster_ConfigContent string,
	Name string,
	Organization Organization,
	Variant KubeProviderVariantT,

) KubeProvider {

	response := &kubeProviderS{}
	client.call(
		"KubeProviderCreate",
		req_KubeProviderCreateS{
			ExistingCluster_ConfigContent: ExistingCluster_ConfigContent,
			Name:                          Name,
			Organization:                  Organization.ID(),
			Variant:                       Variant,
		},
		response,
	)
	return response
}

// ----------------------------------------------------- table list:

type kubeProviderList interface {
	NotValid() bool
	InfoAddTrace(result out.ResultT, msg string, skipFrames int)
	InfoAddCause(parent out.Info) out.Info
	InfoAddVar(name string, value any) out.Info
	InfoResult() out.ResultT
	InfoTraces() []out.TraceS
	InfoLastTrace() out.TraceS
	InfoJSON() []byte
	InfoPrint()

	Length() int
	First() KubeProvider
	GetByID(id string) KubeProvider
	Iter() []KubeProvider
	Refresh() out.Info
	SetWhere(where string) out.Info
	SetOrder(order string) out.Info
	SetOffset(offset int) out.Info
	SetLimit(limit int) out.Info

	AddListener(dl binding.DataListener)
	RemoveListener(dl binding.DataListener)
	GetItem(index int) (binding.DataItem, error)
}

type kubeProviderListS struct {
	out.DontUseMeInfoS

	query   req_listQueryS
	IDs     []string
	IDtoIdx map[string]int
	M       map[string]*kubeProviderS

	dataListener map[binding.DataListener]bool
}

func (o *kubeProviderListS) InfoJSON() []byte {
	buf, _ := json.MarshalIndent(o, "", "  ")
	return buf
}

func (o *kubeProviderListS) InfoPrint() {
	fmt.Println(string(o.InfoJSON()))
}

func (o *kubeProviderListS) AddListener(dl binding.DataListener) {
	// fmt.Println("KubeProviderList AddListener")
	if o.dataListener == nil {
		o.dataListener = map[binding.DataListener]bool{}
	}
	o.dataListener[dl] = true
}

func (o *kubeProviderListS) RemoveListener(dl binding.DataListener) {
	// fmt.Println("KubeProviderList RemoveListener")
	delete(o.dataListener, dl)
}

func (o *kubeProviderListS) GetItem(index int) (binding.DataItem, error) {
	// fmt.Println("KubeProviderList GetItem")
	return o.M[o.IDs[index]], nil
}

func (o *kubeProviderListS) Length() int {
	// fmt.Println("KubeProviderList Length")
	return len(o.IDs)
}

//---

func KubeProviderList(where, order string, offset, limit int) kubeProviderList {

	response := &kubeProviderListS{
		query: req_listQueryS{
			Where:  where,
			Order:  order,
			Offset: offset,
			Limit:  limit,
		},
	}

	if where == "nil" {
		return response
	}

	response.Refresh()
	return response
}

func (o *kubeProviderListS) SetWhere(where string) out.Info {
	o.query = req_listQueryS{
		Where: where,
	}
	return o.Refresh()
}

func (o *kubeProviderListS) SetOrder(order string) out.Info {
	o.query = req_listQueryS{
		Order: order,
	}
	return o.Refresh()
}

func (o *kubeProviderListS) SetOffset(offset int) out.Info {
	o.query = req_listQueryS{
		Offset: offset,
	}
	return o.Refresh()
}

func (o *kubeProviderListS) SetLimit(limit int) out.Info {
	o.query = req_listQueryS{
		Limit: limit,
	}
	return o.Refresh()
}

func (o *kubeProviderListS) First() KubeProvider {
	for _, obj := range o.M {
		return out.CatchError(obj, nil)
	}

	res := &kubeProviderS{}
	res.InfoAddTrace(out.NotFound, "", 0)
	return res
}

func (o *kubeProviderListS) Iter() []KubeProvider {

	if o.NotValid() {
		return nil
	}

	res := []KubeProvider{}
	for _, id := range o.IDs {
		res = append(res, out.CatchError(o.M[id], nil))
	}
	return res
}

func (o *kubeProviderListS) Refresh() out.Info {

	if o.query.Where == "nil" {
		return o
	}

	response := &kubeProviderListS{
		query:        o.query,
		IDs:          []string{},
		IDtoIdx:      map[string]int{},
		M:            map[string]*kubeProviderS{},
		dataListener: o.dataListener,
	}

	client.call(
		"KubeProviderList",
		o.query,
		response,
	)
	*o = *response

	for dl := range o.dataListener {
		// fmt.Println(">>>>>>>>>>>>>>>>>> dataListener", dl)
		dl.DataChanged()
	}
	return o
}

func (o *kubeProviderListS) GetByID(id string) KubeProvider {
	return out.CatchError(o.M[id], nil)
}

//---

func (o *kubeProviderListS) GetByName(name string) KubeProvider {

	for _, obj := range o.M {
		if obj.NameC == name {
			return out.CatchError(obj, nil)
		}
	}

	res := &kubeProviderS{}
	res.InfoAddTrace(out.NotFound, "", 0)
	return res
}
