// Code generated by "stringer -type=EnvPerm"; DO NOT EDIT.

package permissions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Env_View-0]
	_ = x[Env_Rename-1]
	_ = x[Env_ManageSchedule-2]
	_ = x[Env_ManageCluster-3]
	_ = x[Env_ManageGitOPS-4]
	_ = x[Env_ManageTags-5]
	_ = x[Env_ElementVersionChangeOnly-6]
	_ = x[Env_ElementStartStopRestart-7]
	_ = x[Env_ElementTerminal-8]
	_ = x[Env_ElementFullManage-9]
	_ = x[Env_ViewLogsEvents-10]
	_ = x[Env_ViewLogsBuild-11]
	_ = x[Env_ViewLogsRuntime-12]
	_ = x[Env_ViewMembers-13]
	_ = x[Env_ManageMembers-14]
	_ = x[Env_ViewMetrics-15]
	_ = x[Env_ManageMetrics-16]
	_ = x[Env_CopyAndViewSecrets-17]
	_ = x[__Env_Iter-18]
}

const _EnvPerm_name = "Env_ViewEnv_RenameEnv_ManageScheduleEnv_ManageClusterEnv_ManageGitOPSEnv_ManageTagsEnv_ElementVersionChangeOnlyEnv_ElementStartStopRestartEnv_ElementTerminalEnv_ElementFullManageEnv_ViewLogsEventsEnv_ViewLogsBuildEnv_ViewLogsRuntimeEnv_ViewMembersEnv_ManageMembersEnv_ViewMetricsEnv_ManageMetricsEnv_CopyAndViewSecrets__Env_Iter"

var _EnvPerm_index = [...]uint16{0, 8, 18, 36, 53, 69, 83, 111, 138, 157, 178, 196, 213, 232, 247, 264, 279, 296, 318, 328}

func (i EnvPerm) String() string {
	if i >= EnvPerm(len(_EnvPerm_index)-1) {
		return "EnvPerm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EnvPerm_name[_EnvPerm_index[i]:_EnvPerm_index[i+1]]
}
