// Code generated by "stringer -type=GlobPerm"; DO NOT EDIT.

package permissions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Glob_AccessToWebUI-0]
	_ = x[Glob_AccessToAdminZone-1]
	_ = x[Glob_AccessToKube-2]
	_ = x[Glob_ManageGlobalMemebers-3]
	_ = x[Glob_CreateAndDeleteEnvs-4]
	_ = x[Glob_CreateAndDeleteGitRepos-5]
	_ = x[__Glob_Iter-6]
}

const _GlobPerm_name = "Glob_AccessToWebUIGlob_AccessToAdminZoneGlob_AccessToKubeGlob_ManageGlobalMemebersGlob_CreateAndDeleteEnvsGlob_CreateAndDeleteGitRepos__Glob_Iter"

var _GlobPerm_index = [...]uint8{0, 18, 40, 57, 82, 106, 134, 145}

func (i GlobPerm) String() string {
	if i >= GlobPerm(len(_GlobPerm_index)-1) {
		return "GlobPerm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GlobPerm_name[_GlobPerm_index[i]:_GlobPerm_index[i+1]]
}
