// Code generated by "stringer -type=RepoPerm"; DO NOT EDIT.

package permissions

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Repo_View-0]
	_ = x[Repo_Pull-1]
	_ = x[Repo_Push-2]
	_ = x[Repo_RemoteManage-3]
	_ = x[Repo_LocalManage-4]
	_ = x[Repo_SettingsManage-5]
	_ = x[__Repo_Iter-6]
}

const _RepoPerm_name = "Repo_ViewRepo_PullRepo_PushRepo_RemoteManageRepo_LocalManageRepo_SettingsManage__Repo_Iter"

var _RepoPerm_index = [...]uint8{0, 9, 18, 27, 44, 60, 79, 90}

func (i RepoPerm) String() string {
	if i >= RepoPerm(len(_RepoPerm_index)-1) {
		return "RepoPerm(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RepoPerm_name[_RepoPerm_index[i]:_RepoPerm_index[i+1]]
}
