{
 "title": "Varnish",
 "description": "A dashboard to use to debug a running varnish instance. Easily track requests, cache hits, network i/o, sessions, threads, bans, ban lurker and the ban list size",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "varnish_instance",
    "label": "Instance",
    "query": "label_values(varnish_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster",
   "targets": [
    {}
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(varnish_main_backend_req{instance=~\"^$varnish_instance.*\"}[5m])"
    }
   ]
  },
  {
   "title": "Loaded VMODs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(varnish_main_vmods{instance=~\"^($varnish_instance).*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(varnish_main_uptime{instance=~\"^($varnish_instance).*\"})"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(( rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m]) ))"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_main_backend_req{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(varnish_main_fetch_total{instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "fetch total"
    },
    {
     "expr": "sum(irate(varnish_main_fetch_total{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "fetched objects"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "cache hit %"
    },
    {
     "expr": "avg(1 - (rate(varnish_main_cache_hit{instance=~\"^($varnish_instance).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m])))",
     "legendFormat": "cache miss %"
    },
    {
     "expr": "avg(1 - (rate(varnish_main_cache_hitpass{instance=~\"^($varnish_instance).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($varnish_instance).*\"}[5m])))",
     "legendFormat": "cache hit pass %"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{instance=~\"^($varnish_instance).*\"}[5m]) + irate(varnish_main_s_resp_bodybytes{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{instance=~\"^($varnish_instance).*\"}[5m]) + irate(varnish_backend_beresp_bodybytes{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{instance=~\"^($varnish_instance).*\"}[5m]) + irate(varnish_backend_beresp_bodybytes{instance=~\"^($varnish_instance).*\"}[5m])) by (backend)",
     "legendFormat": "backend {{ backend }}"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(varnish_main_n_expired{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_moved{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "LRU moved"
    },
    {
     "expr": "sum(irate(varnish_main_n_lru_nuked{instance=~\"^($varnish_instance).*\"}[5m]))",
     "legendFormat": "LRU nuked"
    },
    {
     "expr": "sum(varnish_sma_g_bytes{type=\"s0\", instance=~\"^($varnish_instance).*\"})",
     "legendFormat": "mem used"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backend Connections (per minute)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(varnish_main_backend_conn{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Backend conn. success"
    },
    {
     "expr": "rate(varnish_main_backend_recycle{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Backend conn. recycles"
    },
    {
     "expr": "rate(varnish_main_backend_reuse{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Backend conn. reuses"
    },
    {
     "expr": "rate(varnish_main_backend_fail{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Backend conn. failures"
    },
    {
     "expr": "rate(varnish_main_backend_unhealthy{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Backend conn. not attempted"
    },
    {
     "expr": "rate(varnish_main_backend_busy{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Backend conn. too many"
    },
    {
     "expr": "rate(varnish_main_backend_req{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Backend requests made"
    },
    {
     "expr": "rate(varnish_main_backend_retry{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Backend conn. retry"
    },
    {
     "expr": "rate(varnish_backend_conn{instance=~\"^($varnish_instance).*\"}[1m])",
     "legendFormat": "Concurrent connections to backend"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (rate(varnish_main_sessions{instance=~\"^($varnish_instance).*\"}[1m]))",
     "legendFormat": "session - {{type}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "varnish_main_threads_created{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Threads created"
    },
    {
     "expr": "varnish_main_threads_destroyed{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Threads destroyed"
    },
    {
     "expr": "varnish_main_threads_failed{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Thread creation failed"
    },
    {
     "expr": "varnish_main_threads_limited{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Max Threads hit"
    },
    {
     "expr": "varnish_main_threads{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Total number of threads"
    },
    {
     "expr": "varnish_main_thread_queue_len{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Length of session queue waiting for threads"
    },
    {
     "expr": "varnish_main_pools{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Number of thread pools   "
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bans",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "varnish_main_bans{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Count of Bans"
    },
    {
     "expr": "varnish_main_bans_completed{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Number of bans marked 'completed'"
    },
    {
     "expr": "varnish_main_bans_deleted{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Bans deleted"
    },
    {
     "expr": "varnish_main_bans_dups{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Bans superseded by other bans"
    },
    {
     "expr": "varnish_main_bans_obj{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Number of bans using obj.*"
    },
    {
     "expr": "varnish_main_bans_obj_killed{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Objects killed by bans (lookup)"
    }
   ]
  },
  {
   "title": "Size of Ban Lists",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "varnish_main_bans_persisted_bytes{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Bytes used by the persisted ban lists"
    },
    {
     "expr": "varnish_main_bans_persisted_fragmentation{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Extra bytes in persisted ban lists due to fragmentation"
    }
   ]
  },
  {
   "title": "Ban Lurker",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "varnish_main_bans_lurker_contention{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Lurker gave way for lookup"
    },
    {
     "expr": "varnish_main_bans_lurker_obj_killed{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Objects killed by bans (lurker)"
    },
    {
     "expr": "varnish_main_bans_lurker_tested{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Bans tested against objects (lurker)"
    },
    {
     "expr": "varnish_main_bans_lurker_tests_tested{instance=~\"^($varnish_instance).*\"}",
     "legendFormat": "Ban tests tested against objects (lurker)"
    }
   ]
  }
 ]
}