{
 "title": "Kubernetes pod and cluster monitoring (via Prometheus)",
 "description": "Monitor a Kubernetes cluster using Prometheus TSDB.  Shows overall cluster CPU / Memory / Disk usage as well as individual pod statistics.\r\n\r\nModified version of dashboard #162 to work with Prometheus 2.1+. \r\n\r\nNote - Managed Kubernetes instances (such as Azure AKS) might not give you access to FS stats, as you can see in the screenshot. You should be able to see those stats otherwise.",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Application",
    "query": {
     "query": "label_values(kube_namespace_created,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU  /  number of cpu cores used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace)( rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$Application\"}[1m] ) ) *2",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Network IO receive",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (rate(container_network_receive_bytes_total{namespace!=\"\",interface=\"eth0\",namespace=~\"$Application\"}[1m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Memory  /  amount of RAM used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum(container_memory_usage_bytes{image!=\"\",namespace=~\"$Application\"}) by (namespace))",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Network IO transmit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace) (rate(container_network_transmit_bytes_total{namespace!=\"\",interface=\"eth0\",namespace=~\"$Application\"}[1m])))",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}